version: '3.4'

services:
  n5permissionsfrontend:
    image: n5permissionsfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
